# Generated by Django 3.2.3 on 2021-05-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_prduct_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_order', to='products.Order', verbose_name='Заказы покупателя'),
        ),
    ]
