# Generated by Django 3.2.3 on 2021-06-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210604_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сериный номер товара'),
        ),
    ]
