# Generated by Django 3.2.3 on 2021-06-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, default=models.CharField(max_length=255, verbose_name='Именование'), max_length=50, verbose_name='Сериный номер товара'),
        ),
    ]
